from recipe_site.admin.recipe import RecipeAdmin
from recipe_site.admin.ingredient import IngredientAdmin
from recipe_site.admin.recipe_ingredient import RecipeIngredientAdmin
from recipe_site.admin.dietary_category import DietaryCategoryAdmin
