# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site_data', '0002_auto_20160705_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietarycategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
