# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site_data', '0003_auto_20160705_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietarycategory',
            options={'verbose_name_plural': 'dietary categories'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_category',
            field=models.ManyToManyField(blank=True, null=True, to='recipe_site_data.DietaryCategory'),
        ),
    ]
