# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_site_data', '0004_auto_20160705_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dietary_category',
            field=models.ManyToManyField(blank=True, to='recipe_site_data.DietaryCategory'),
        ),
    ]
